import * as Clipboard from 'expo-clipboard';
import { Alert } from 'react-native';

export interface ReportData {
  period: string;
  received: number;
  negative: number;
  avgRating: string;
  growth: string;
  ratingDist: number[];
  issue: string;
  issuePercent: number;
  activity?: number[];
  activityLabels?: string[];
}

import { useAlertStore } from '../store/AlertStore';

/**
 * Fallback export service
 * Since expo-print and expo-sharing require native module installation 
 * which may be restricted in this environment, we provide a clipboard fallback.
 */
export const exportReportToPDF = async (data: ReportData, t: any) => {
  const reportText = generateReportText(data, t);

  try {
    // Copy to clipboard
    await Clipboard.setStringAsync(reportText);

    // Inform the user
    useAlertStore.getState().showAlert({
      title: "Report Copied",
      message: "PDF Export requires additional setup in your local environment. We have copied the report data to your clipboard as a formatted summary for you to paste elsewhere.",
      type: 'info'
    });
  } catch (error) {
    console.error('Error copying to clipboard:', error);
    throw error;
  }
};

const generateReportText = (data: ReportData, t: any) => {
  const dateStr = new Date().toLocaleDateString();
  
  return `OPINOR BUSINESS REPORT
------------------------
Date: ${dateStr}
Period: ${data.period}

SUMMARY:
- Received Feedbacks: ${data.received}
- Negative Feedbacks: ${data.negative}
- Average Rating: ${data.avgRating}
- Growth: ${data.growth}

RATING DISTRIBUTION:
- 1 Star: ${data.ratingDist[4]}%
- 2 stars: ${data.ratingDist[3]}%
- 3 stars: ${data.ratingDist[2]}%
- 4 stars: ${data.ratingDist[1]}%
- 5 stars: ${data.ratingDist[0]}%

CRITICAL INSIGHT:
Main Issue: ${data.issue} (${data.issuePercent}% of negative feedbacks)

Generated by Opinor`;
};
